[package]
name = "squadcfg"
version = "0.1.0"
authors = ["Paul d'Hubert <paul@tymate.com>"]
edition = "2018"

[dependencies]
itertools = "~0.9.0"
pest = "~2.1.3"
pest_derive = "~2.1.0"
seahorse = "~0.7.1"
