root = { rule* }
rule = { (group | player | comment) ~ NEWLINE*}
group = { "Group=" ~ group_name ~ ":" ~ permissions }
group_name = { ASCII_ALPHANUMERIC+ }
permissions = { (perm ~ comma?)* }
perm = { ASCII_ALPHA+ }
comma = _{ "," }
player = { "Admin=" ~ player_name ~ ":" ~ group_name ~ " "? ~ comment? }
player_name = { ASCII_ALPHANUMERIC* }
comment = { comment_start ~ comment_content }
comment_content =  { (ASCII_ALPHANUMERIC | " ")* }
comment_start = _{ "//" }
